### ISSUE TITLE
Car Maint for Print

### ISSUE THREAD

**Issue by andrea7even** [mkinitcpio/car-maintenance#57]
Hello, Can you  add please, car km, euro, and the possibility to print the page (for example the notes or the comment for clients), thanks

Здравствуйте, не могли бы вы добавить, пожалуйста, автомобильный км, евро и возможность распечатать страницу (например, заметки или комментарий для клиентов), спасибо

**Comment by mkinitcpio** [comment]
Добрый день. В каком виде вы вообще печать (списком, таблицей)?
Было бы не плохо посмотреть на то, что вы хотите.

**Comment by mkinitcpio** [comment]
#58

**Comment by andrea7even** [comment]
привет, я думаю, неплохо иметь возможность распечатать список всю страницу в целом

hi, i think it's nice to be able to print the list the whole page in general

**Comment by mkinitcpio** [comment]
В целом можно, но могут быть проблемы с комментариями (из за слишком длинного текста таблица может поехать).
В следующей версии добавлю редактирование единиц измерения.

Если будут еще какие-то предложения, пишите.

**Comment by andrea7even** [comment]
однако вы можете распечатать страницу дважды, чтобы получить все списки, если она не помещается только на одной. Я думаю, что минимум 5 машин умещаются на печатной странице

**Comment by andrea7even** [comment]
однако вы можете распечатать страницу дважды, чтобы получить все списки, если она не помещается только на одной. Я думаю, что минимум 5 машин умещаются на печатной странице

**Comment by mkinitcpio** [comment]
А вот это уже интересно…
Я изначально задумывал проект для использования одной машины и в будущем собирался добавить поддержку нескольких машин. 
Можно сказать, что вы ее адаптировали под свои нужды 😅

**Comment by mkinitcpio** [comment]
Было бы интересно узнать вашу структуру: то есть что вы указываете на первом уровне, что на втором.

**Comment by andrea7even** [comment]
![FEAAD07F-0A46-4D33-B2EF-B67A9EDDD0A0](https://user-images.githubusercontent.com/72453254/145006861-a1848adf-db9b-4bed-98eb-0cc62f68212e.jpeg)

вот как я создал настраиваемую страницу, печать такая, как вы ее видите

here's how I created the custom page, the print is as you see it

**Comment by mkinitcpio** [comment]
А в колонке Name, что вы записываете?

**Comment by andrea7even** [comment]
the work done on the machine in the workshop. distribution chain, price €, car pads, €, etc ..

работа проделана на станке в мастерской. дистрибьюторская сеть, цена €, автомобильные колодки, € и т. д.

**Comment by mkinitcpio** [comment]
Возможно мы недопоняли друг друга.

Список (пункт 1 на картинке), как я понял у вас содержит марку машины. Во вложенном списке клиенты?

Имя в таблице (пункт 2) - это название дистрибьюторских сетей

![5DFD2AFB-291D-43E6-A97C-063DBB304C81](https://user-images.githubusercontent.com/12542028/145014240-a0006d73-5c2b-43f4-a0dc-79be7edc52f0.jpeg)

**Comment by mkinitcpio** [comment]
Ah, do you prefer Russian or English lang in discussion?

**Comment by andrea7even** [comment]
I write in English because maybe there are some users who don't understand Russian and maybe they are interested in the speech

**Comment by mkinitcpio** [comment]
Okay. So, as I wrote previously, I will emplement editable units in 2.5 version. Printing feature will be implement in 2.6 version
